### PR TITLE
Selfhosted version improvements

### LINKED ISSUE #133: email server without authentication
Hi, thank you for creating/open-sourcing plausible.io!

It's just what I wanted for personal/hobby projects and very easy to setup / migrate to it (I think it took me less than 1 hour to set it up and migrate all my personal projects from google analytics)

Some questions popped up, most of them already have issues with the `self-hosted ` label, but one I couldn't find is: how do I have to set the environment variables if my email server doesn't require auth?

I noticed in [the config](https://github.com/plausible/analytics/blob/master/config/config.exs#L146) auth is set to `:always`. It appears there's also a `:if_available` setting [documented in bamboo_smtp](https://github.com/fewlinesco/bamboo_smtp/blob/39a27e7f9879aa4f494abba2d3275b82e93f59d1/lib/bamboo/adapters/smtp_adapter.ex#L27) -- assuming it does what I think, would it be possible to use that or, probably even better, make the option configurable?

Not sure how easy it is, but including a "send me a test email" button would be very helpful

### LINKED ISSUE #198: Setting db poolsizes for postgres and clickhouse gives me a kernel dum
Setting db poolsizes for postgres and clickhouse gives me a kernel dump;

I am not sure why its DATABASE_POOL_SIZE instead of DATABASE_POOLSIZE for postgres, but either way the kernel hiccups.

DATABASE_POOL_SIZE=20
CLICKHOUSE_DATABASE_POOLSIZE=20

> {"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.DBConnection.ConnectionPool',{{badmatch,{error,{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<\"ranges (first..last) expect both sides to be integers, got: 1..\\"20\\"\">>},[{'Elixir.Range',new,2,[{file,\"lib/range.ex\"},{line,63}]},{'Elixir.DBConnection.ConnectionPool.Pool',init,1,[{file,\"lib/db_connection/connection_pool/pool.ex\"},{line,18}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,295}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},[{'Elixir.DBConnection.ConnectionPool',init,1,[{file,\"lib/db_connection/connection_pool.ex\"},{line,22}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{'Elixir.Plausible.Application',start,[normal,[]]}}}"}
> Kernel pid terminated (application_controller) ({application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.DBConnection.ConnectionPool',{{badmatch,{error,{#{'__exception__' => true

### PR DESCRIPTION
**Pull request by tckb**
This PR will address some of the concerns raised during the self-hosted versions:

closes https://github.com/plausible/analytics/issues/26, closes https://github.com/plausible/analytics/issues/85, closes https://github.com/plausible/analytics/issues/86, closes https://github.com/plausible/analytics/issues/88, closes #133 

- [x] cleanup docker-compose 
- [x] separate migration step 
- [x] remove/skip plausible.io landing page for self-hosting setup 
- [x] optionally enable registration page
- [x] optionally enable sign-in page
- [x] add tests
- [x] remove landing page and other unused templates
- [x]  remove `Joken` dependenc
- [x]  fix the app page to show login/register instead of "trial period"
- [x]  fix config param inconsistency issue and invalid value to param - closes #198

### CODE REVIEW

**Comment by ukutaht** [comment]
I still don't see much reason to keep it tbh. If someone has a fork and they're adding code for a landing page, it shouldn't be a big ask to also change the `Pagecontroller.Index` handler to render the landing page instead of doing redirection.

Instead of referencing an old landing page we don't use anymore, it would be better to reference the code for our [live landing page](https://github.com/plausible/website/blob/master/index.html).

The main reason I want to remove it is because our CSS is compiled based on the classes used in the actual HTML templates. By removing the landing page we remove some of Tailwind's CSS classes from being included in the final build. This would make the whole app lighter.

**Comment by tckb** [comment]
> The main reason I want to remove it is because our CSS is compiled based on the classes used in the actual HTML templates. By removing the landing page we remove some of Tailwind's CSS classes from being included in the final build. This would make the whole app lighter.

Agreed. okay, so removing the templates at https://github.com/plausible/analytics/tree/master/lib/plausible_web/templates/page would suffice right?

**Comment by ukutaht** [comment]
> Okay, I agree on the size part. So removing the templates at https://github.com/plausible/analytics/tree/master/lib/plausible_web/templates/page would suffice right?

Yeah, and changing the controller to redirect based on the login state here:
https://github.com/plausible/analytics/blob/master/lib/plausible_web/controllers/page_controller.ex#L25

**Comment by tckb** [comment]
> Yeah, and changing the controller to redirect based on the login state here:

This is already handled by [auto_auth_plyg](https://github.com/tckb/plausible/blob/master/lib/plausible_web/plugs/auto_auth_plug.ex). 

I will remove unnecessary assets and templates to needed for self-hosting

**Comment by ukutaht** [comment]
Cool 👍 I will merge once those are removed

**Comment by ukutaht** [comment]
One more thing, let's make the landing page disabled by default.

**Comment by tckb** [comment]
> One more thing, let's make the landing page disabled by default.
 
If I remove the template, then there wouldn't be any landing page :P  I am not sure if I understand this correctly

File: lib/plausible_web/controllers/page_controller.ex [hunk 1]
```diff
@@ -1,98 +1,14 @@
...
-  end
-
-  defp sign_token!(user) do
-    claims = %{
-      id: user.id,
-      email: user.email,
-      name: user.name
-    }
-
-    signer = Joken.Signer.create("HS256", "4d1d2ae6-4595-4d0b-b98a-8ca5b1f2095a")
```
Comment (ukutaht) [inline lib/plausible_web/controllers/page_controller.ex:49]: Can remove the `Joken` dependency, this is the only place it was used.

File: lib/plausible_web/controllers/page_controller.ex [hunk 2]
```diff
@@ -1,98 +1,14 @@
...
-      redirect(conn, external: "https://plausible.nolt.io/roadmap")
-    end
-  end
-
-  def contact_form(conn, _params) do
-    render(conn, "contact_form.html")
-  end
-
-  def submit_contact_form(conn, %{"text" => text, "email" => email}) do
-    PlausibleWeb.Email.feedback(email, text) |> Plausible.Mailer.send_email()
```
Comment (ukutaht) [inline lib/plausible_web/controllers/page_controller.ex:81]: Can remove the `def feedback` definition and the associated template from `PlausibleWeb.Email`

File: lib/plausible_web/templates/layout/app.html.eex [hunk 3]
```diff
@@ -52,11 +52,8 @@
                 <% true -> %>
                   <ul class="flex" x-show="!document.cookie.includes('logged_in=true')">
                     <li>
-                      <div class="inline-flex">
-                        <a href="/login" class="font-medium text-gray-500 hover:text-gray-900 focus:outline-none focus:text-gray-900 transition duration-150 ease-in-out">Login</a>
-                      </div>
                       <div class="inline-flex rounded shadow ml-6">
-                        <a href="/register" class="inline-flex items-center justify-center px-5 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out">Start free trial</a>
```
Comment (ukutaht) [inline lib/plausible_web/templates/layout/app.html.eex:59]: I realize that showing 'Start free trial' doesn't make a lot of sense for self-hosters, but I feel like we should keep a button that says 'Sign up' or 'Register' (if registration is enabled in config).

File: lib/plausible_web/controllers/page_controller.ex (hunk 1 above)
Comment (tckb) [reply lib/plausible_web/controllers/page_controller.ex:49]: cool! I will remove it.

File: lib/plausible_web/controllers/page_controller.ex (hunk 2 above)
Comment (tckb) [reply lib/plausible_web/controllers/page_controller.ex:81]: @ukutaht  the feedback definition from page_controller is removed.  the template `PlausibleWeb.Email`  where is it located?

File: lib/plausible_web/templates/layout/app.html.eex (hunk 3 above)
Comment (tckb) [reply lib/plausible_web/templates/layout/app.html.eex:59]: As per the new changes: 

_Landing page_ is disabled by default so, "/" will be redirected to the login page. 



image



There the "register" button is enabled _conditionally_  and will be redirected to the signup page. These changes only apply to the landing page(which is hidden, will _always_ direct to login)

File: lib/plausible_web/controllers/page_controller.ex (hunk 2 above)
Comment (ukutaht) [reply lib/plausible_web/controllers/page_controller.ex:81]: Function definition: https://github.com/plausible/analytics/blob/master/lib/plausible_web/email.ex#L103

And I was wrong, there's no template for that email as the content is just passed through. The function definition can go.

File: lib/plausible_web/templates/layout/app.html.eex (hunk 3 above)
Comment (ukutaht) [reply lib/plausible_web/templates/layout/app.html.eex:59]: > These changes only apply to the landing page

They apply anywhere the default layout`layout/app.html` is rendered which includes the live demo and all public sites.
 The `Start free trial` can be seen in the live demo here:

Screenshot 2020-06-29 at 14 50 48

I want to make sure the navbar of the live demo and public sites has a button to the registration page. This is why I'm suggesting we make this button appear conditionally as on the login page.

Comment (tckb) [reply lib/plausible_web/templates/layout/app.html.eex:59]: Arm, you're right! I didn't even realize it (I didn't have a hosted version to test it, before). Makes sense. I will change "Start free trial" to "Register" if this available or, this will be login.
